### PR TITLE
feat(ESLint): Bump eslint and eslint config

### PR DESCRIPTION
**Pull request by n-srg**
- Bump eslint-config-tradeshift

### CODE REVIEW

**Comment by n-srg** [comment]
image

**Comment by wejendorp** [comment]
I'm not sure this is the right place for this kind of opinionated rules. The jest rules that we're adding here are mostly preventing common mistakes with the test suites.

The message etc is nice though. We could consider adding it to https://github.com/Tradeshift/eslint-config-tradeshift

**Comment by n-srg** [comment]
ahhhh i see. sorry I mixed repos
@wejendorp check this one https://github.com/Tradeshift/eslint-config-tradeshift/pull/30

**Comment by n-srg** [comment]
npm publish

**Comment by n-srg** [comment]
npm publish

**Comment by wejendorp** [comment]
We merged this. Thanks :)

**Pull request closed without merging**
