### PR TITLE
chore: add lockfile for security alerts

### PR DESCRIPTION
**Pull request by wejendorp**

### CODE REVIEW

**Review by NimaZahedi — APPROVED** [review]

**Comment by tstapleton** [comment]
we need lockfiles for security reasons? I've been removing it from packages since I saw https://github.com/Tradeshift/legacy-ts-lib.js/pull/57.

**Comment by wejendorp** [comment]
@tstapleton afaik dependabot is only able to do security / automated bumps if you have the package-lock / yarn lock. So I've been adding them back :innocent:

**Comment by tstapleton** [comment]
We get dependabot PRs for https://github.com/Tradeshift/appcues without a package lock. Security ones are different? Or maybe cause of the dependabot config file?

**Pull request merged**
