### PR TITLE
fix(jest): use axios cjs

### PR DESCRIPTION
**Pull request by tradeshift-larsbojensen**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by tradeshift-larsbojensen** [comment]
npm publish

**Comment by tradeshift-larsbojensen** [comment]
It does not fix the issue I have with shop-apps unit tests: `TypeError: Cannot read properties of undefined (reading 'CancelToken')`, This happens when testing components that use [Client.fromContext](https://github.com/Tradeshift/tradeshift.js/blob/4b3405a7409d3d7898f4060e9343d4507c120ca7/src/index.ts#L157)

**Comment by seriouslag** [comment]
> It does not fix the issue I have with shop-apps unit tests: `TypeError: Cannot read properties of undefined (reading 'CancelToken')`, This happens when testing components that use [Client.fromContext](https://github.com/Tradeshift/tradeshift.js/blob/4b3405a7409d3d7898f4060e9343d4507c120ca7/src/index.ts#L157)

Hey @tradeshift-larsbojensen, thanks for looking at this.

shop-apps uses v4 for testing, this change is the same as the v4 fix.

Here a PR of the v4 changes used in shop-apps to have a successful test/build:
https://github.com/Tradeshift/shop-apps/pull/1244

**Comment by seriouslag** [comment]
npm publish

**Comment by seriouslag** [comment]
@tradeshift-larsbojensen, my understanding is we still need these changes to be merged.

This PR has the same fix we implemented in v4.

thoughts on reopening this?

**Comment by tradeshift-larsbojensen** [comment]
@seriouslag You are right. I just opened https://github.com/Tradeshift/tradeshift-scripts/pull/237

**Pull request closed without merging**
